language: csharp
mono: none
os: linux
dist: bionic
dotnet: 2.2
script:
- dotnet restore --no-cache
- dotnet build -c Release --no-restore
- dotnet test
- nuget pack
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push *.nupkg --source "https://api.nuget.org/v3/index.json" --api-key $NUGET_API_KEY
  on:
    branch: master
    tags: true
