version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5438:5432"
    networks:
      - udressy
  eventbus:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - udressy
  aspnetcore.eventlog.sample1:
    image: aspnetcoreeventlogsample1
    build:
      context: .
      dockerfile: AspNetCore.EventLog.Sample1/Dockerfile
    depends_on:
      - db
      - eventbus
    ports:
      - "8080:80"
    networks:
      - udressy
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=giacomo.m@centropaghe.it
      - PGADMIN_DEFAULT_PASSWORD=giacomo
    ports:
      - "5439:80"
    networks:
      - udressy
networks:
  udressy:
